management-console:
  protocol: https
  host: 172.17.0.1
  servlet-transport-port: 9443
  servelet-transport-port-http: 9763

api-manager:
  nio-pt-transport-port: 8243

apis:
  - name: news
    context: news
    version: 1
    resources:
      - method: GET
        path: menu
      - method: POST
        path: order

  - name: payment
    context: places
    version: 1
    resources:
      - method: GET
        path: menu

