management_console:
  protocol: https
  host: 172.17.0.1
  servlet_transport_port_https: 9443
  servlet_transport_port_http: 9763

api_manager:
  nio_pt_transport_port: 8243

apis:
  - name: news
    context: news
    version: 1
    resources:
      - method: GET
        path: menu

  - name: payment
    context: places
    version: 1
    resources:
      - method: GET
        path: menu
