management_console:
  protocol: https
  host: 172.17.0.1
  servlet_transport_port_https: 9443
  servlet_transport_port_http: 9763

api_manager:
  nio_pt_transport_port: 8243

apis:
#  - name: news
#    context: news
#    version: 1
#    resources:
#     - method: GET
#       path: menu
      

#  - name: places
#    context: places
#    version: 1
#    resources:
#      - method: GET
#        path: menu

  - name: payment
    context: payment
    version: 1
    resources:
      - method: GET
        path: menu
      - method: POST
        path: order

#  - name: map
#    context: map
#    version: 1
#    resources:
#      - method: GET
#        path: menu
      
#  - name: weather
#    context: weather
#    version: 1
#    resources:
#      - method: GET
#        path: menu

#  - name: cricket
#    context: cricket
#    version: 1
#    resources:
#      - method: GET
#        path: menu
